apiVersion: v1
kind: Service
metadata:
    name: ${artifactId}-svc
    labels:
        app: ${artifactId}
spec:
    type: NodePort
    ports:
    - port: 8080
      nodePort: 30020
      protocol: TCP
    selector:
      app: ${artifactId}
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: ${artifactId}-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            app: ${artifactId}
    minReadySeconds: 10
    template:
        metadata:
            labels:
                app: ${artifactId}
            containers:
            - name: ${artifactId}-pod
              image: ${artifactId}:latest
              ports:
              - containerPort: 8080