apiVersion: v1
kind: Service
metadata:
    name: basic-svc
    labels:
        app: basic
spec:
    type: NodePort
    ports:
    - port: 8080
      nodePort: 30020
      protocol: TCP
    selector:
      app: basic
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: basic-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            app: basic
    minReadySeconds: 10
    template:
        metadata:
            labels:
                app: basic
            containers:
            - name: basic-pod
              image: basic:latest
              ports:
              - containerPort: 8080